# Generated by Django 3.1.1 on 2022-02-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='publish_date',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
