# Generated by Django 3.1.1 on 2022-03-12 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('shop', '0009_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkoutPage',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('checkoutItems', models.CharField(max_length=50)),
            ],
        ),
    ]
