# Generated by Django 3.1.1 on 2022-02-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20220222_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='publish_date',
            field=models.DateTimeField(default=0),
        ),
    ]
