# Generated by Django 3.1.1 on 2022-03-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkoutItems',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
