# Generated by Django 3.1.1 on 2022-02-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20220223_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='publish_date',
            field=models.DateTimeField(default='22/02/2022'),
        ),
    ]
