# Generated by Django 3.1.1 on 2022-02-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20220223_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='publish_date',
            field=models.DateTimeField(),
        ),
    ]
